---
- name: Playbook to copy files
  become: true
  hosts: localhost
  tasks:

                          - name: Copy files with owner and permisions
                            copy:
                                                src: /etc/lucky.txt
                                                dest: /usr/
                                                owner: root
                                                group: root
                                                mode: '0644'
