---
- name: Playbook to copy files
  become: true
  hosts: localhost
  tasks:

                          - name: Copy files with owner and permisions
                            copy:
                                                src: /home/lucky/Downloads/ansible-tower-setup-latest.tar.gz
                                                dest: /home/lucky/Documents
                                                owner: lucky
                                                group: lucky
                                                mode: '0644'
